/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package macpan;

public class InstructionsFrame extends javax.swing.JFrame {

    //Main window variable
    MenuFrame mainWindow;
    
    /**
     * Creates the instructions frame with gui builder
     * @param m - the main window
     */
    public InstructionsFrame(MenuFrame m) {
        initComponents();
        //Set frame to middle of screen, title, and disallow rezizing
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Instructions");
        mainWindow = m;
        instructionArea.setText("Instructions:\n" +
"Eat all of the pellets to clear the entire maze\n" +
"You have 3 lives at the start\n" +
"If a ghost catches you, you lose a life\n" +
"When you lose all your lives, the game is over\n" +
"\n" +
"Tips and Tricks:\n" +
"Power Pellets: \n" +
"When Pac Man eats the power pellets, he can now eat the ghosts!\n" +
"But he can only eat them when the ghosts become scared \n" +
"but this will only last for a limited time so be careful!\n" +
"Fruit Treats:\n" +
"Two fruits appear in each maze. \n" +
"As you complete more levels, the more they are worth\n" +
"Warp Tunnels:\n" +
"Go through one end and you will warp out the other end\n" +
"Use these tunnels to your advantage!\n" +
"\n" +
"Scoring:\n" +
"Pellet: 10 points\n" +
"Power Pellet: 50 points\n" +
"Ghosts:\n" +
"1st Ghost - 200 points\n" +
"2nd Ghost 400 points\n" +
"3rd Ghost - 800 points\n" +
"4th Ghost - 1600 points\n" +
"Fruit:\n" +
"Cherry - 100 points\n" +
"Strawberry - 200 points\n" +
"Orange - 300 points\n" +
"Extra Life:\n" +
"You gain an extra life at every 10,000 points!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        instructionArea.setColumns(20);
        instructionArea.setRows(5);
        jScrollPane2.setViewportView(instructionArea);

        jLabel1.setText("INSTRUCTIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //If back button is clicked..
        this.setVisible(false); //Instructionsframe is not visible
        mainWindow.setVisible(true); //Main window is visible
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea instructionArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
