/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package macpan;

import java.awt.Color;

public class InstructionsFrame extends javax.swing.JFrame {

    //Main window variable
    MenuFrame mainWindow;
    
    /**
     * Creates the instructions frame with gui builder
     * @param m - the main window
     */
    public InstructionsFrame(MenuFrame m) {
        initComponents();
        //Set frame to middle of screen, title, and disallow rezizing
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Instructions");
        getContentPane().setBackground(Color.BLACK);
        mainWindow = m;
        instructionArea.setText("""
                                Instructions:
                                Eat all of the pellets to clear the entire maze
                                You have 3 lives at the start
                                If a ghost catches you, you lose a life
                                When you lose all your lives, the game is over
                                
                                Tips and Tricks:
                                Power Pellets: 
                                When PacMan eats power pellets, he can now eat the ghosts!
                                But he can only eat them when the ghosts become\nscared 
                                but this will only last for a limited time so \nbe careful!
                                Fruit Treats:
                                Two fruits appear in each maze. 
                                As you complete more levels, the more they are worth
                                Warp Tunnels:
                                Go through one end and you will warp out the \nother end
                                Use these tunnels to your advantage!
                                
                                Scoring:
                                Pellet: 10 points
                                Power Pellet: 50 points
                                Ghosts:
                                1st Ghost - 200 points
                                2nd Ghost 400 points
                                3rd Ghost - 800 points
                                4th Ghost - 1600 points
                                Fruit:
                                Cherry - 100 points
                                Strawberry - 200 points
                                Orange - 300 points
                                Extra Life:
                                You gain an extra life at every 10,000 points!""");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 222, 9));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        instructionArea.setBackground(new java.awt.Color(0, 0, 0));
        instructionArea.setColumns(20);
        instructionArea.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        instructionArea.setForeground(new java.awt.Color(255, 222, 9));
        instructionArea.setLineWrap(true);
        instructionArea.setRows(5);
        instructionArea.setAutoscrolls(false);
        instructionArea.setBorder(null);
        instructionArea.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(instructionArea);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 222, 9));
        jLabel1.setText("INSTRUCTIONS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //If back button is clicked..
        this.setVisible(false); //Instructionsframe is not visible
        mainWindow.setVisible(true); //Main window is visible
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea instructionArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}