/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package macpan;

public class InstructionsFrame extends javax.swing.JFrame {

    //Main window variable
    MenuFrame mainWindow;
    
    /**
     * Creates the instructions frame with gui builder
     * @param m - the main window
     */
    public InstructionsFrame(MenuFrame m) {
        initComponents();
        //Set frame to middle of screen, title, and disallow rezizing
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Instructions");
        mainWindow = m;
        instructionArea.setText("""
                                Instructions:
                                Eat all of the pellets to clear the entire maze
                                You have 3 lives at the start
                                If a ghost catches you, you lose a life
                                When you lose all your lives, the game is over
                                
                                Tips and Tricks:
                                Power Pellets: 
                                When Pac Man eats the power pellets, he can now eat the ghosts!
                                But he can only eat them when the ghosts become scared 
                                but this will only last for a limited time so be careful!
                                Fruit Treats:
                                Two fruits appear in each maze. 
                                As you complete more levels, the more they are worth
                                Warp Tunnels:
                                Go through one end and you will warp out the other end
                                Use these tunnels to your advantage!
                                
                                Scoring:
                                Pellet: 10 points
                                Power Pellet: 50 points
                                Ghosts:
                                1st Ghost - 200 points
                                2nd Ghost 400 points
                                3rd Ghost - 800 points
                                4th Ghost - 1600 points
                                Fruit:
                                Cherry - 100 points
                                Strawberry - 200 points
                                Orange - 300 points
                                Extra Life:
                                You gain an extra life at every 10,000 points!""");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        instructionArea.setColumns(20);
        instructionArea.setRows(5);
        jScrollPane2.setViewportView(instructionArea);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setText("INSTRUCTIONS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //If back button is clicked..
        this.setVisible(false); //Instructionsframe is not visible
        mainWindow.setVisible(true); //Main window is visible
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea instructionArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}